// This file is auto-generated by @hey-api/openapi-ts

export { client, type CreateClientConfig } from './client.gen';
export { type Options, SimpleWorkspaceViews } from './sdk.gen';
export type { ClientOptions, GetRenderByWorkspaceViewData, GetRenderByWorkspaceViewErrors, GetRenderByWorkspaceViewResponse, GetRenderByWorkspaceViewResponses, SimpleWorkspaceViewRenderModel } from './types.gen';
