// This file is auto-generated by @hey-api/openapi-ts

export const $SimpleWorkspaceViewRenderModel = {
    required: ['body'],
    type: 'object',
    properties: {
        body: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;