// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetUmbracoSimpleWorkspaceViewsApiV1RenderByWorkspaceViewData, GetUmbracoSimpleWorkspaceViewsApiV1RenderByWorkspaceViewResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.workspaceView
 * @returns unknown OK
 * @throws ApiError
 */
export const getUmbracoSimpleWorkspaceViewsApiV1RenderByWorkspaceView = (data: GetUmbracoSimpleWorkspaceViewsApiV1RenderByWorkspaceViewData): CancelablePromise<GetUmbracoSimpleWorkspaceViewsApiV1RenderByWorkspaceViewResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/SimpleWorkspaceViews/api/v1/render/{workspaceView}',
    path: {
        workspaceView: data.workspaceView
    }
}); };