// This file is auto-generated by @hey-api/openapi-ts

export type SimpleWorkspaceViewRenderModel = {
    body: string;
};

export type GetUmbracoSimpleWorkspaceViewsApiV1RenderByWorkspaceViewData = {
    workspaceView: string;
};

export type GetUmbracoSimpleWorkspaceViewsApiV1RenderByWorkspaceViewResponse = ((SimpleWorkspaceViewRenderModel));