name: 🏗️ Build
on:
  pull_request:
    branches: "*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: jcdcdev/jcdcdev.Umbraco.Github.Build@main
        with:
          project-name: Umbraco.Community.SimpleWorkspaceViews
          project-path: src/Umbraco.Community.SimpleWorkspaceViews/Umbraco.Community.SimpleWorkspaceViews.csproj
          npm-working-dir: src/Umbraco.Community.SimpleWorkspaceViews.Client
          npm-enabled: true
          umbraco-version: 14